### ISSUE TITLE
please update other methods and if possible add cfb. thanks

### ISSUE THREAD

**Issue by NuxLO49** [levanderdev/XeriaC2#1]
╔══Xeria@C2
╚==>OVH
Command: [ OVH ] Not Found!
╔══Xeria@C2
╚==>http-api
Command: [ http-api ] Not Found!
╔══Xeria@C2
╚==>http-raw
Command: [ http-raw ] Not Found!
╔══Xeria@C2
╚==>http-post
Command: [ http-post ] Not Found!
╔══Xeria@C2
╚==>http-pro
Command: [ http-pro ] Not Found!
╔══Xeria@C2
╚==>xeriatls
Command: [ xeriatls ] Not Found!
╔══Xeria@C2
╚==>http-get
Usage: http-get <url> <time>
Example: http-get http://example.com 60
╔══Xeria@C2
╚==>

**Comment by levanderdev** [comment]
the version free sorry i added method now but im bussy so its don't python XeriaC2.py but you can cd XeriaC2 and python udp.py node HTTP-RAW.js or what so i no add the panel im so sorry

**Comment by levanderdev** [comment]
Update

**Comment by NuxLO49** [comment]
thank you very much bro
